# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x32\x45\n\x04GRPC\x12=\n\x0eGetCoordinates\x12\x16.google.protobuf.Empty\x1a\x11.grpc.Coordinates\"\x00\x42:\n\x15io.grpc.examples.grpcB\tgRPCProtoP\x01\xa2\x02\x03GRP\xaa\x02\rRPCDemoClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.examples.grpcB\tgRPCProtoP\001\242\002\003GRP\252\002\rRPCDemoClient'
  _COORDINATES._serialized_start=49
  _COORDINATES._serialized_end=84
  _GRPC._serialized_start=86
  _GRPC._serialized_end=155
# @@protoc_insertion_point(module_scope)
